import { CanvasPreset } from './types';

export const CANVAS_PRESETS: CanvasPreset[] = [
  {
    id: 'insta-square',
    name: 'Instagram Post (Quadrado)',
    category: 'Redes Sociais',
    width: 1080,
    height: 1080,
  },
  {
    id: 'insta-portrait',
    name: 'Instagram Carrossel / Retrato',
    category: 'Redes Sociais',
    width: 1080,
    height: 1350,
  },
  {
    id: 'insta-story',
    name: 'Stories / Reels / TikTok',
    category: 'Redes Sociais',
    width: 1080,
    height: 1920,
  },
  {
    id: 'meta-ads',
    name: 'Anúncio Meta / Facebook Ads',
    category: 'Tráfego & Anúncios',
    width: 1200,
    height: 628,
  },
  {
    id: 'yt-thumb',
    name: 'YouTube Thumbnail',
    category: 'Vídeo',
    width: 1280,
    height: 720,
  },
  {
    id: 'banner-web',
    name: 'Banner Web / Header',
    category: 'Web',
    width: 1920,
    height: 1080,
  },
  {
    id: 'flyer-a4',
    name: 'Cartaz / Flyer / A4',
    category: 'Impresso & PDF',
    width: 1240,
    height: 1754,
  },
  {
    id: 'business-card',
    name: 'Cartão de Visita / Mini Banner',
    category: 'Impresso & PDF',
    width: 1050,
    height: 600,
  },
];

export const FONT_FAMILIES = [
  { name: 'Inter (Modern Sans)', value: 'Inter, system-ui, sans-serif' },
  { name: 'Montserrat (Geométrico & Forte)', value: 'Montserrat, sans-serif' },
  { name: 'Playfair Display (Luxo & Editorial)', value: '"Playfair Display", Georgia, serif' },
  { name: 'Bebas Neue (Display & Chamadas)', value: '"Bebas Neue", Impact, sans-serif' },
  { name: 'Anton (Impacto & Título)', value: 'Anton, sans-serif' },
  { name: 'Poppins (Arredondado & Suave)', value: 'Poppins, sans-serif' },
  { name: 'Cinzel (Clássico & Premium)', value: 'Cinzel, Georgia, serif' },
  { name: 'Pacifico (Manuscrito Divertido)', value: 'Pacifico, cursive' },
  { name: 'Caveat (Assinatura & Humano)', value: 'Caveat, cursive' },
  { name: 'JetBrains Mono (Tech & Código)', value: '"JetBrains Mono", monospace' },
];

export const COLOR_PALETTES = [
  '#000000',
  '#0e1117',
  '#1f2937',
  '#ffffff',
  '#f3f4f6',
  '#ef4444',
  '#f97316',
  '#f59e0b',
  '#eab308',
  '#10b981',
  '#06b6d4',
  '#3b82f6',
  '#6366f1',
  '#8b5cf6',
  '#ec4899',
  '#f43f5e',
  '#d97706',
  '#14b8a6',
  '#84cc16',
  '#0ea5e9',
];

export const GRADIENT_PRESETS = [
  {
    name: 'Dark Luxury (Preto + Dourado)',
    colors: ['#0f0f12', '#221e16', '#090a0f'],
    angle: 135,
  },
  {
    name: 'Cyber Neon (Azul + Roxo)',
    colors: ['#090d16', '#2b1055', '#7597de'],
    angle: 45,
  },
  {
    name: 'Sunset Glow (Laranja + Rosa)',
    colors: ['#f43f5e', '#fb923c', '#fef08a'],
    angle: 120,
  },
  {
    name: 'Emerald Matrix (Verde + Preto)',
    colors: ['#062014', '#0d5939', '#10b981'],
    angle: 90,
  },
  {
    name: 'Deep Oceanic (Azul Marinho + Ciano)',
    colors: ['#031024', '#0a3663', '#06b6d4'],
    angle: 180,
  },
  {
    name: 'Clean Studio (Cinza Claro)',
    colors: ['#f8fafc', '#e2e8f0', '#cbd5e1'],
    angle: 135,
  },
  {
    name: 'Purple Magic (Roxo + Magenta)',
    colors: ['#3b0764', '#701a75', '#d946ef'],
    angle: 135,
  },
  {
    name: 'Midnight Gold (Obsidiana + Champanhe)',
    colors: ['#121212', '#2a2415', '#dfb86c'],
    angle: 45,
  },
];

export const STOCK_PHOTOS = [
  {
    id: 'p1',
    category: 'Negócios & Corporativo',
    title: 'Executivo em Reunião',
    thumb: 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?auto=format&fit=crop&w=600&q=80',
    full: 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?auto=format&fit=crop&w=1400&q=90',
  },
  {
    id: 'p2',
    category: 'Negócios & Corporativo',
    title: 'Mulher de Negócios Confiante',
    thumb: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=600&q=80',
    full: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=1400&q=90',
  },
  {
    id: 'p3',
    category: 'Tecnologia & IA',
    title: 'Glow Futurista & Dados',
    thumb: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=600&q=80',
    full: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=1400&q=90',
  },
  {
    id: 'p4',
    category: 'Tecnologia & IA',
    title: 'Smartphone & Dashboard',
    thumb: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=600&q=80',
    full: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1400&q=90',
  },
  {
    id: 'p5',
    category: 'Luxo & Lifestyle',
    title: 'Arquitetura Minimalista & Luz',
    thumb: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=600&q=80',
    full: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1400&q=90',
  },
  {
    id: 'p6',
    category: 'Luxo & Lifestyle',
    title: 'Relógio e Estilo Premium',
    thumb: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=600&q=80',
    full: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1400&q=90',
  },
  {
    id: 'p7',
    category: 'Marketing & Vendas',
    title: 'Sucesso & Celebração',
    thumb: 'https://images.unsplash.com/photo-1531545514256-b1400bc00f31?auto=format&fit=crop&w=600&q=80',
    full: 'https://images.unsplash.com/photo-1531545514256-b1400bc00f31?auto=format&fit=crop&w=1400&q=90',
  },
  {
    id: 'p8',
    category: 'Marketing & Vendas',
    title: 'Café, Laptop e Planejamento',
    thumb: 'https://images.unsplash.com/photo-1499750310107-5fef28a66643?auto=format&fit=crop&w=600&q=80',
    full: 'https://images.unsplash.com/photo-1499750310107-5fef28a66643?auto=format&fit=crop&w=1400&q=90',
  },
  {
    id: 'p9',
    category: 'Texturas & Fundos',
    title: 'Gradiente Dark Abstrato',
    thumb: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=600&q=80',
    full: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1400&q=90',
  },
  {
    id: 'p10',
    category: 'Texturas & Fundos',
    title: 'Ondas de Luz Líquidas 3D',
    thumb: 'https://images.unsplash.com/photo-1634017839464-5c339ebe3cb4?auto=format&fit=crop&w=600&q=80',
    full: 'https://images.unsplash.com/photo-1634017839464-5c339ebe3cb4?auto=format&fit=crop&w=1400&q=90',
  },
  {
    id: 'p11',
    category: 'Saúde & Fitness',
    title: 'Treino e Alta Performance',
    thumb: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=600&q=80',
    full: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=1400&q=90',
  },
  {
    id: 'p12',
    category: 'Gastronomia',
    title: 'Burger Artesanal & Prato Gourmet',
    thumb: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=600&q=80',
    full: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=1400&q=90',
  },
];

export const BADGE_STICKERS = [
  {
    id: 'b-50off',
    title: '50% OFF',
    text: '50% OFF',
    bgColor: '#ef4444',
    textColor: '#ffffff',
    shape: 'rounded-rect',
  },
  {
    id: 'b-frete',
    title: 'FRETE GRÁTIS',
    text: 'FRETE GRÁTIS',
    bgColor: '#10b981',
    textColor: '#ffffff',
    shape: 'rounded-rect',
  },
  {
    id: 'b-garantia',
    title: 'GARANTIA 7 DIAS',
    text: '🛡️ GARANTIA TOTAL',
    bgColor: '#3b82f6',
    textColor: '#ffffff',
    shape: 'rounded-rect',
  },
  {
    id: 'b-vagas',
    title: 'ÚLTIMAS VAGAS',
    text: '🔥 VAGAS LIMITADAS',
    bgColor: '#f97316',
    textColor: '#ffffff',
    shape: 'rounded-rect',
  },
  {
    id: 'b-linkbio',
    title: 'LINK NA BIO',
    text: '👉 LINK NA BIO',
    bgColor: '#8b5cf6',
    textColor: '#ffffff',
    shape: 'rounded-rect',
  },
  {
    id: 'b-arraste',
    title: 'ARRASTE PRO LADO',
    text: '👉 ARRASTE PARA O LADO',
    bgColor: '#ffffff',
    textColor: '#000000',
    shape: 'rounded-rect',
  },
  {
    id: 'b-stars',
    title: '5 ESTRELAS',
    text: '⭐⭐⭐⭐⭐ 5.0 (Excelente)',
    bgColor: '#f59e0b',
    textColor: '#000000',
    shape: 'rounded-rect',
  },
  {
    id: 'b-novidade',
    title: 'NOVIDADE EXCLUSIVA',
    text: '✨ NOVIDADE',
    bgColor: '#ec4899',
    textColor: '#ffffff',
    shape: 'rounded-rect',
  },
  {
    id: 'b-clique',
    title: 'SAIBA MAIS',
    text: 'CLIQUE NO LINK ↗',
    bgColor: '#22c55e',
    textColor: '#000000',
    shape: 'rounded-rect',
  },
];

export const SOCIAL_ICONS = [
  { id: 'icon-insta', name: 'Instagram', emoji: '📸', color: '#e1306c' },
  { id: 'icon-whats', name: 'WhatsApp', emoji: '💬', color: '#25d366' },
  { id: 'icon-yt', name: 'YouTube', emoji: '▶️', color: '#ff0000' },
  { id: 'icon-meta', name: 'Facebook / Meta', emoji: '🌐', color: '#1877f2' },
  { id: 'icon-tiktok', name: 'TikTok', emoji: '🎵', color: '#000000' },
  { id: 'icon-star', name: 'Estrela', emoji: '⭐', color: '#f59e0b' },
  { id: 'icon-fire', name: 'Fogo / Destaque', emoji: '🔥', color: '#f97316' },
  { id: 'icon-zap', name: 'Raio / Velocidade', emoji: '⚡', color: '#eab308' },
  { id: 'icon-check', name: 'Verificado', emoji: '✅', color: '#10b981' },
  { id: 'icon-lock', name: 'Segurança / Cadeado', emoji: '🔒', color: '#6366f1' },
  { id: 'icon-target', name: 'Alvo / Meta', emoji: '🎯', color: '#ef4444' },
  { id: 'icon-trophy', name: 'Troféu / Vitória', emoji: '🏆', color: '#f59e0b' },
];

export const TYPOGRAPHY_PRESETS = [
  {
    id: 't-headline-dark',
    name: 'Headline Impactante',
    title: 'DESCUBRA O MÉTODO SECRETO',
    font: '"Bebas Neue", Impact, sans-serif',
    size: 72,
    color: '#ffffff',
    weight: '900',
    bg: '#ef4444',
    bgPadding: 16,
    bgRadius: 8,
  },
  {
    id: 't-luxury-serif',
    name: 'Luxo & Sofisticação',
    title: 'Elegância em Cada Detalhe',
    font: '"Playfair Display", Georgia, serif',
    size: 54,
    color: '#dfb86c',
    weight: '700',
    fontStyle: 'italic',
  },
  {
    id: 't-neon-glow',
    name: 'Cyberpunk Neon Glow',
    title: 'NOVA ERA DIGITAL',
    font: 'Montserrat, sans-serif',
    size: 64,
    color: '#06b6d4',
    weight: '900',
    shadowColor: '#06b6d4',
    shadowBlur: 25,
  },
  {
    id: 't-minimal-bold',
    name: 'Minimalista & Editorial',
    title: 'Menos é Mais.',
    font: 'Inter, system-ui, sans-serif',
    size: 58,
    color: '#ffffff',
    weight: '800',
    letterSpacing: -1,
  },
  {
    id: 't-handwritten',
    name: 'Manuscrito Casual',
    title: 'Feito com carinho para você',
    font: 'Caveat, cursive',
    size: 64,
    color: '#fef08a',
    weight: '600',
  },
];
