import { CanvasTemplate } from './types';

export const CANVA_TEMPLATES: CanvasTemplate[] = [
  {
    id: 'template-promo-black',
    name: 'Oferta Especial & Black Friday',
    category: 'Vendas & Promoções',
    description: 'Design de alto impacto com contraste preto, vermelho e dourado para promoções.',
    width: 1080,
    height: 1080,
    background: {
      type: 'gradient',
      color: '#0a0a0d',
      gradient: {
        type: 'linear',
        colors: ['#0d0e12', '#1c0f12', '#08080a'],
        angle: 135,
      },
    },
    elements: [
      {
        id: 'bg-shape-glow',
        type: 'shape',
        shapeType: 'circle',
        x: 240,
        y: 200,
        width: 600,
        height: 600,
        rotation: 0,
        opacity: 0.15,
        locked: false,
        zIndex: 1,
        fillColor: '#ef4444',
        strokeColor: 'transparent',
        strokeWidth: 0,
      },
      {
        id: 'badge-top',
        type: 'shape',
        shapeType: 'rounded-rect',
        x: 340,
        y: 110,
        width: 400,
        height: 54,
        rotation: 0,
        opacity: 1,
        locked: false,
        zIndex: 2,
        fillColor: '#ef4444',
        strokeColor: 'transparent',
        strokeWidth: 0,
        borderRadius: 27,
      },
      {
        id: 'text-badge',
        type: 'text',
        text: '🔥 CONDIÇÃO POR TEMPO LIMITADO',
        x: 350,
        y: 124,
        width: 380,
        height: 30,
        rotation: 0,
        opacity: 1,
        locked: false,
        zIndex: 3,
        fontFamily: 'Inter, system-ui, sans-serif',
        fontSize: 16,
        fontWeight: '800',
        fontStyle: 'normal',
        textAlign: 'center',
        color: '#ffffff',
        letterSpacing: 1,
        lineHeight: 1.2,
      },
      {
        id: 'title-main',
        type: 'text',
        text: 'SUPER OFERTA\nIMPERDÍVEL',
        x: 100,
        y: 220,
        width: 880,
        height: 180,
        rotation: 0,
        opacity: 1,
        locked: false,
        zIndex: 4,
        fontFamily: '"Bebas Neue", Impact, sans-serif',
        fontSize: 88,
        fontWeight: '900',
        fontStyle: 'normal',
        textAlign: 'center',
        color: '#ffffff',
        letterSpacing: 2,
        lineHeight: 0.95,
        shadowColor: 'rgba(239, 68, 68, 0.4)',
        shadowBlur: 20,
      },
      {
        id: 'card-discount',
        type: 'shape',
        shapeType: 'rounded-rect',
        x: 290,
        y: 440,
        width: 500,
        height: 220,
        rotation: 0,
        opacity: 1,
        locked: false,
        zIndex: 5,
        fillColor: '#181920',
        strokeColor: '#333644',
        strokeWidth: 2,
        borderRadius: 24,
      },
      {
        id: 'text-discount-tag',
        type: 'text',
        text: 'ATÉ',
        x: 320,
        y: 480,
        width: 440,
        height: 25,
        rotation: 0,
        opacity: 0.8,
        locked: false,
        zIndex: 6,
        fontFamily: 'Inter, system-ui, sans-serif',
        fontSize: 18,
        fontWeight: '700',
        fontStyle: 'normal',
        textAlign: 'center',
        color: '#9ca3af',
        letterSpacing: 4,
        lineHeight: 1.2,
      },
      {
        id: 'text-discount-val',
        type: 'text',
        text: '50% OFF',
        x: 320,
        y: 515,
        width: 440,
        height: 100,
        rotation: 0,
        opacity: 1,
        locked: false,
        zIndex: 7,
        fontFamily: 'Montserrat, sans-serif',
        fontSize: 76,
        fontWeight: '900',
        fontStyle: 'normal',
        textAlign: 'center',
        color: '#22c55e',
        letterSpacing: -1,
        lineHeight: 1,
      },
      {
        id: 'btn-cta',
        type: 'shape',
        shapeType: 'rounded-rect',
        x: 260,
        y: 740,
        width: 560,
        height: 80,
        rotation: 0,
        opacity: 1,
        locked: false,
        zIndex: 8,
        fillColor: '#ffffff',
        strokeColor: 'transparent',
        strokeWidth: 0,
        borderRadius: 40,
      },
      {
        id: 'text-btn-cta',
        type: 'text',
        text: 'GARANTIR MEU DESCONTO ➔',
        x: 280,
        y: 766,
        width: 520,
        height: 35,
        rotation: 0,
        opacity: 1,
        locked: false,
        zIndex: 9,
        fontFamily: 'Montserrat, sans-serif',
        fontSize: 22,
        fontWeight: '900',
        fontStyle: 'normal',
        textAlign: 'center',
        color: '#000000',
        letterSpacing: 0.5,
        lineHeight: 1.2,
      },
      {
        id: 'footer-notes',
        type: 'text',
        text: 'www.suaempresa.com.br | @seuinstagram',
        x: 100,
        y: 930,
        width: 880,
        height: 30,
        rotation: 0,
        opacity: 0.6,
        locked: false,
        zIndex: 10,
        fontFamily: 'Inter, system-ui, sans-serif',
        fontSize: 18,
        fontWeight: '500',
        fontStyle: 'normal',
        textAlign: 'center',
        color: '#9ca3af',
        letterSpacing: 2,
        lineHeight: 1.2,
      },
    ],
  },
  {
    id: 'template-masterclass-launch',
    name: 'Masterclass & Lançamento High-End',
    category: 'Lançamentos & Aulas',
    description: 'Layout moderno com foto de autoridade e estética minimalista dark.',
    width: 1080,
    height: 1080,
    background: {
      type: 'gradient',
      color: '#0b0c10',
      gradient: {
        type: 'linear',
        colors: ['#090a0f', '#121724', '#05070a'],
        angle: 150,
      },
    },
    elements: [
      {
        id: 'photo-speaker',
        type: 'image',
        src: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=800&q=80',
        x: 540,
        y: 200,
        width: 480,
        height: 640,
        rotation: 0,
        opacity: 0.9,
        locked: false,
        zIndex: 1,
        borderRadius: 24,
        contrast: 105,
      },
      {
        id: 'tag-live',
        type: 'shape',
        shapeType: 'rounded-rect',
        x: 80,
        y: 100,
        width: 220,
        height: 44,
        rotation: 0,
        opacity: 1,
        locked: false,
        zIndex: 2,
        fillColor: '#ef4444',
        strokeColor: 'transparent',
        strokeWidth: 0,
        borderRadius: 12,
      },
      {
        id: 'text-tag-live',
        type: 'text',
        text: '🔴 AULA AO VIVO',
        x: 90,
        y: 112,
        width: 200,
        height: 25,
        rotation: 0,
        opacity: 1,
        locked: false,
        zIndex: 3,
        fontFamily: 'Inter, system-ui, sans-serif',
        fontSize: 15,
        fontWeight: '800',
        fontStyle: 'normal',
        textAlign: 'center',
        color: '#ffffff',
        letterSpacing: 1,
        lineHeight: 1.2,
      },
      {
        id: 'title-headline',
        type: 'text',
        text: 'ESCALANDO\nSUA AGÊNCIA\nPARA 7 DÍGITOS',
        x: 80,
        y: 200,
        width: 440,
        height: 220,
        rotation: 0,
        opacity: 1,
        locked: false,
        zIndex: 4,
        fontFamily: 'Montserrat, sans-serif',
        fontSize: 44,
        fontWeight: '900',
        fontStyle: 'normal',
        textAlign: 'left',
        color: '#ffffff',
        letterSpacing: -0.5,
        lineHeight: 1.05,
      },
      {
        id: 'subtitle-copy',
        type: 'text',
        text: 'O passo a passo estratégico para atrair clientes de alto valor e criar esteiras previsíveis de faturamento.',
        x: 80,
        y: 460,
        width: 400,
        height: 120,
        rotation: 0,
        opacity: 0.85,
        locked: false,
        zIndex: 5,
        fontFamily: 'Inter, system-ui, sans-serif',
        fontSize: 18,
        fontWeight: '400',
        fontStyle: 'normal',
        textAlign: 'left',
        color: '#cbd5e1',
        letterSpacing: 0,
        lineHeight: 1.5,
      },
      {
        id: 'box-date',
        type: 'shape',
        shapeType: 'rounded-rect',
        x: 80,
        y: 620,
        width: 400,
        height: 80,
        rotation: 0,
        opacity: 1,
        locked: false,
        zIndex: 6,
        fillColor: '#1e293b',
        strokeColor: '#334155',
        strokeWidth: 1.5,
        borderRadius: 16,
      },
      {
        id: 'text-date',
        type: 'text',
        text: '🗓️ 15 DE OUTUBRO • ÀS 20H\n100% ONLINE E GRATUITO',
        x: 100,
        y: 638,
        width: 360,
        height: 50,
        rotation: 0,
        opacity: 1,
        locked: false,
        zIndex: 7,
        fontFamily: 'Inter, system-ui, sans-serif',
        fontSize: 16,
        fontWeight: '700',
        fontStyle: 'normal',
        textAlign: 'center',
        color: '#38bdf8',
        letterSpacing: 0.5,
        lineHeight: 1.3,
      },
      {
        id: 'btn-sub',
        type: 'shape',
        shapeType: 'rounded-rect',
        x: 80,
        y: 740,
        width: 400,
        height: 70,
        rotation: 0,
        opacity: 1,
        locked: false,
        zIndex: 8,
        fillColor: '#0ea5e9',
        strokeColor: 'transparent',
        strokeWidth: 0,
        borderRadius: 16,
      },
      {
        id: 'text-btn-sub',
        type: 'text',
        text: 'QUERO ME INSCREVER ➔',
        x: 90,
        y: 762,
        width: 380,
        height: 30,
        rotation: 0,
        opacity: 1,
        locked: false,
        zIndex: 9,
        fontFamily: 'Montserrat, sans-serif',
        fontSize: 18,
        fontWeight: '900',
        fontStyle: 'normal',
        textAlign: 'center',
        color: '#ffffff',
        letterSpacing: 0.5,
        lineHeight: 1.2,
      },
    ],
  },
  {
    id: 'template-luxury-branding',
    name: 'Branding de Luxo & Frase Editorial',
    category: 'Branding & Citações',
    description: 'Tipografia serif clássica com tons dourados e fundo obsidiana premium.',
    width: 1080,
    height: 1080,
    background: {
      type: 'gradient',
      color: '#0d0d0f',
      gradient: {
        type: 'linear',
        colors: ['#121318', '#08080a', '#1a1812'],
        angle: 45,
      },
    },
    elements: [
      {
        id: 'frame-border',
        type: 'shape',
        shapeType: 'rectangle',
        x: 60,
        y: 60,
        width: 960,
        height: 960,
        rotation: 0,
        opacity: 0.35,
        locked: true,
        zIndex: 1,
        fillColor: 'transparent',
        strokeColor: '#dfb86c',
        strokeWidth: 1.5,
      },
      {
        id: 'brand-top',
        type: 'text',
        text: 'A G E N C Y   E X C L U S I V E',
        x: 100,
        y: 140,
        width: 880,
        height: 30,
        rotation: 0,
        opacity: 0.8,
        locked: false,
        zIndex: 2,
        fontFamily: 'Cinzel, Georgia, serif',
        fontSize: 16,
        fontWeight: '700',
        fontStyle: 'normal',
        textAlign: 'center',
        color: '#dfb86c',
        letterSpacing: 4,
        lineHeight: 1.2,
      },
      {
        id: 'quote-mark',
        type: 'text',
        text: '“',
        x: 100,
        y: 240,
        width: 880,
        height: 100,
        rotation: 0,
        opacity: 0.3,
        locked: false,
        zIndex: 3,
        fontFamily: '"Playfair Display", Georgia, serif',
        fontSize: 140,
        fontWeight: '700',
        fontStyle: 'italic',
        textAlign: 'center',
        color: '#dfb86c',
        letterSpacing: 0,
        lineHeight: 0.5,
      },
      {
        id: 'quote-body',
        type: 'text',
        text: 'O verdadeiro posicionamento não grita por atenção. Ele atrai com precisão e elegância os clientes que reconhecem o seu valor.',
        x: 140,
        y: 380,
        width: 800,
        height: 240,
        rotation: 0,
        opacity: 1,
        locked: false,
        zIndex: 4,
        fontFamily: '"Playfair Display", Georgia, serif',
        fontSize: 34,
        fontWeight: '600',
        fontStyle: 'italic',
        textAlign: 'center',
        color: '#f8fafc',
        letterSpacing: 0.5,
        lineHeight: 1.55,
      },
      {
        id: 'divider-line',
        type: 'shape',
        shapeType: 'line',
        x: 440,
        y: 690,
        width: 200,
        height: 4,
        rotation: 0,
        opacity: 0.6,
        locked: false,
        zIndex: 5,
        fillColor: '#dfb86c',
        strokeColor: '#dfb86c',
        strokeWidth: 2,
      },
      {
        id: 'author-name',
        type: 'text',
        text: 'DIRETORIA DE MARCA',
        x: 100,
        y: 730,
        width: 880,
        height: 30,
        rotation: 0,
        opacity: 0.9,
        locked: false,
        zIndex: 6,
        fontFamily: 'Inter, system-ui, sans-serif',
        fontSize: 15,
        fontWeight: '800',
        fontStyle: 'normal',
        textAlign: 'center',
        color: '#dfb86c',
        letterSpacing: 3,
        lineHeight: 1.2,
      },
      {
        id: 'author-handle',
        type: 'text',
        text: '@sua.agencia.oficial',
        x: 100,
        y: 770,
        width: 880,
        height: 25,
        rotation: 0,
        opacity: 0.5,
        locked: false,
        zIndex: 7,
        fontFamily: 'Inter, system-ui, sans-serif',
        fontSize: 14,
        fontWeight: '400',
        fontStyle: 'normal',
        textAlign: 'center',
        color: '#9ca3af',
        letterSpacing: 1,
        lineHeight: 1.2,
      },
    ],
  },
  {
    id: 'template-social-proof',
    name: 'Depoimento & Prova Social 5 Estrelas',
    category: 'Prova Social & Reviews',
    description: 'Card de avaliação com 5 estrelas e foto de cliente satisfeito.',
    width: 1080,
    height: 1080,
    background: {
      type: 'color',
      color: '#0f1117',
    },
    elements: [
      {
        id: 'top-tag',
        type: 'text',
        text: 'HISTÓRIA REAL DE SUCESSO',
        x: 100,
        y: 90,
        width: 880,
        height: 30,
        rotation: 0,
        opacity: 0.8,
        locked: false,
        zIndex: 1,
        fontFamily: 'Inter, system-ui, sans-serif',
        fontSize: 16,
        fontWeight: '800',
        fontStyle: 'normal',
        textAlign: 'center',
        color: '#10b981',
        letterSpacing: 3,
        lineHeight: 1.2,
      },
      {
        id: 'heading-main',
        type: 'text',
        text: '“Multiplicamos nossas vendas em 4x no primeiro mês”',
        x: 100,
        y: 150,
        width: 880,
        height: 140,
        rotation: 0,
        opacity: 1,
        locked: false,
        zIndex: 2,
        fontFamily: 'Montserrat, sans-serif',
        fontSize: 44,
        fontWeight: '900',
        fontStyle: 'normal',
        textAlign: 'center',
        color: '#ffffff',
        letterSpacing: -0.5,
        lineHeight: 1.15,
      },
      {
        id: 'stars-rating',
        type: 'text',
        text: '⭐⭐⭐⭐⭐',
        x: 100,
        y: 310,
        width: 880,
        height: 40,
        rotation: 0,
        opacity: 1,
        locked: false,
        zIndex: 3,
        fontFamily: 'Inter, system-ui, sans-serif',
        fontSize: 32,
        fontWeight: '600',
        fontStyle: 'normal',
        textAlign: 'center',
        color: '#f59e0b',
        letterSpacing: 4,
        lineHeight: 1,
      },
      {
        id: 'card-quote',
        type: 'shape',
        shapeType: 'rounded-rect',
        x: 140,
        y: 390,
        width: 800,
        height: 320,
        rotation: 0,
        opacity: 1,
        locked: false,
        zIndex: 4,
        fillColor: '#181b26',
        strokeColor: '#282d3f',
        strokeWidth: 1.5,
        borderRadius: 24,
      },
      {
        id: 'quote-text',
        type: 'text',
        text: 'A equipe entendeu exatamente nosso público e montou campanhas extremamente precisas. O retorno sobre o investimento foi imediato e hoje temos fila de espera de novos clientes!',
        x: 180,
        y: 430,
        width: 720,
        height: 160,
        rotation: 0,
        opacity: 0.9,
        locked: false,
        zIndex: 5,
        fontFamily: 'Inter, system-ui, sans-serif',
        fontSize: 22,
        fontWeight: '400',
        fontStyle: 'normal',
        textAlign: 'center',
        color: '#e2e8f0',
        letterSpacing: 0.2,
        lineHeight: 1.6,
      },
      {
        id: 'client-name',
        type: 'text',
        text: 'Rodrigo Medeiros • CEO da TechFit',
        x: 180,
        y: 620,
        width: 720,
        height: 30,
        rotation: 0,
        opacity: 1,
        locked: false,
        zIndex: 6,
        fontFamily: 'Montserrat, sans-serif',
        fontSize: 18,
        fontWeight: '800',
        fontStyle: 'normal',
        textAlign: 'center',
        color: '#38bdf8',
        letterSpacing: 0.5,
        lineHeight: 1.2,
      },
      {
        id: 'cta-bottom',
        type: 'text',
        text: 'Pronto para ter esses resultados na sua empresa? Toque no link da bio.',
        x: 100,
        y: 840,
        width: 880,
        height: 60,
        rotation: 0,
        opacity: 0.7,
        locked: false,
        zIndex: 7,
        fontFamily: 'Inter, system-ui, sans-serif',
        fontSize: 18,
        fontWeight: '600',
        fontStyle: 'normal',
        textAlign: 'center',
        color: '#94a3b8',
        letterSpacing: 0,
        lineHeight: 1.4,
      },
    ],
  },
  {
    id: 'template-story-reels',
    name: 'Story / Reels Oferta Relâmpago (9:16)',
    category: 'Stories & Reels',
    description: 'Formato vertical 1080x1920 para Instagram Stories, TikTok e Reels.',
    width: 1080,
    height: 1920,
    background: {
      type: 'gradient',
      color: '#08080a',
      gradient: {
        type: 'linear',
        colors: ['#0f051d', '#1e0836', '#090a14'],
        angle: 180,
      },
    },
    elements: [
      {
        id: 'top-urgency',
        type: 'shape',
        shapeType: 'rounded-rect',
        x: 140,
        y: 220,
        width: 800,
        height: 70,
        rotation: 0,
        opacity: 1,
        locked: false,
        zIndex: 1,
        fillColor: '#ec4899',
        strokeColor: 'transparent',
        strokeWidth: 0,
        borderRadius: 35,
      },
      {
        id: 'text-top-urgency',
        type: 'text',
        text: '⚡ APENAS NAS PRÓXIMAS 24 HORAS',
        x: 160,
        y: 242,
        width: 760,
        height: 35,
        rotation: 0,
        opacity: 1,
        locked: false,
        zIndex: 2,
        fontFamily: 'Montserrat, sans-serif',
        fontSize: 20,
        fontWeight: '900',
        fontStyle: 'normal',
        textAlign: 'center',
        color: '#ffffff',
        letterSpacing: 1.5,
        lineHeight: 1.2,
      },
      {
        id: 'story-headline',
        type: 'text',
        text: 'OFERTA\nRELÂMPAGO\nVIP',
        x: 100,
        y: 420,
        width: 880,
        height: 320,
        rotation: 0,
        opacity: 1,
        locked: false,
        zIndex: 3,
        fontFamily: '"Bebas Neue", Impact, sans-serif',
        fontSize: 110,
        fontWeight: '900',
        fontStyle: 'normal',
        textAlign: 'center',
        color: '#ffffff',
        letterSpacing: 3,
        lineHeight: 0.95,
        shadowColor: '#ec4899',
        shadowBlur: 30,
      },
      {
        id: 'story-image',
        type: 'image',
        src: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=800&q=80',
        x: 190,
        y: 840,
        width: 700,
        height: 480,
        rotation: 0,
        opacity: 1,
        locked: false,
        zIndex: 4,
        borderRadius: 32,
      },
      {
        id: 'sticker-discount',
        type: 'shape',
        shapeType: 'circle',
        x: 680,
        y: 780,
        width: 220,
        height: 220,
        rotation: -12,
        opacity: 1,
        locked: false,
        zIndex: 5,
        fillColor: '#f59e0b',
        strokeColor: '#ffffff',
        strokeWidth: 4,
      },
      {
        id: 'text-sticker',
        type: 'text',
        text: '-60%\nOFF',
        x: 700,
        y: 840,
        width: 180,
        height: 100,
        rotation: -12,
        opacity: 1,
        locked: false,
        zIndex: 6,
        fontFamily: 'Montserrat, sans-serif',
        fontSize: 42,
        fontWeight: '900',
        fontStyle: 'normal',
        textAlign: 'center',
        color: '#000000',
        letterSpacing: -1,
        lineHeight: 0.9,
      },
      {
        id: 'story-cta-box',
        type: 'shape',
        shapeType: 'rounded-rect',
        x: 140,
        y: 1500,
        width: 800,
        height: 110,
        rotation: 0,
        opacity: 1,
        locked: false,
        zIndex: 7,
        fillColor: '#ffffff',
        strokeColor: 'transparent',
        strokeWidth: 0,
        borderRadius: 55,
      },
      {
        id: 'text-story-cta',
        type: 'text',
        text: '👆 CLIQUE NO LINK ACIMA',
        x: 160,
        y: 1540,
        width: 760,
        height: 40,
        rotation: 0,
        opacity: 1,
        locked: false,
        zIndex: 8,
        fontFamily: 'Montserrat, sans-serif',
        fontSize: 28,
        fontWeight: '900',
        fontStyle: 'normal',
        textAlign: 'center',
        color: '#000000',
        letterSpacing: 1,
        lineHeight: 1.2,
      },
    ],
  },
  {
    id: 'template-meta-ad-carousel',
    name: 'Anúncio Meta Ads / Feed Retrato (4:5)',
    category: 'Tráfego & Anúncios',
    description: 'Proporção 1080x1350 otimizada para o feed do Instagram com máxima retenção.',
    width: 1080,
    height: 1350,
    background: {
      type: 'gradient',
      color: '#090a0f',
      gradient: {
        type: 'linear',
        colors: ['#0d1117', '#161b22', '#090d16'],
        angle: 135,
      },
    },
    elements: [
      {
        id: 'tag-ad',
        type: 'shape',
        shapeType: 'rounded-rect',
        x: 80,
        y: 80,
        width: 240,
        height: 46,
        rotation: 0,
        opacity: 1,
        locked: false,
        zIndex: 1,
        fillColor: '#22c55e',
        strokeColor: 'transparent',
        strokeWidth: 0,
        borderRadius: 12,
      },
      {
        id: 'text-tag-ad',
        type: 'text',
        text: '🔥 DICA DE PERFORMANCE',
        x: 90,
        y: 93,
        width: 220,
        height: 25,
        rotation: 0,
        opacity: 1,
        locked: false,
        zIndex: 2,
        fontFamily: 'Inter, system-ui, sans-serif',
        fontSize: 14,
        fontWeight: '800',
        fontStyle: 'normal',
        textAlign: 'center',
        color: '#000000',
        letterSpacing: 0.5,
        lineHeight: 1.2,
      },
      {
        id: 'ad-title',
        type: 'text',
        text: '3 ERROS QUE ESTÃO\nQUEIMANDO SEU\nORÇAMENTO DE ADS',
        x: 80,
        y: 170,
        width: 920,
        height: 200,
        rotation: 0,
        opacity: 1,
        locked: false,
        zIndex: 3,
        fontFamily: 'Montserrat, sans-serif',
        fontSize: 52,
        fontWeight: '900',
        fontStyle: 'normal',
        textAlign: 'left',
        color: '#ffffff',
        letterSpacing: -1,
        lineHeight: 1.05,
      },
      {
        id: 'ad-photo',
        type: 'image',
        src: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=900&q=80',
        x: 80,
        y: 420,
        width: 920,
        height: 560,
        rotation: 0,
        opacity: 1,
        locked: false,
        zIndex: 4,
        borderRadius: 24,
      },
      {
        id: 'swipe-card',
        type: 'shape',
        shapeType: 'rounded-rect',
        x: 80,
        y: 1040,
        width: 920,
        height: 160,
        rotation: 0,
        opacity: 1,
        locked: false,
        zIndex: 5,
        fillColor: '#1f2937',
        strokeColor: '#374151',
        strokeWidth: 2,
        borderRadius: 24,
      },
      {
        id: 'swipe-text',
        type: 'text',
        text: '👉 Arraste para o lado para ver o checklist completo e economizar até 40% em cada lead gerado.',
        x: 120,
        y: 1080,
        width: 840,
        height: 80,
        rotation: 0,
        opacity: 0.95,
        locked: false,
        zIndex: 6,
        fontFamily: 'Inter, system-ui, sans-serif',
        fontSize: 22,
        fontWeight: '600',
        fontStyle: 'normal',
        textAlign: 'left',
        color: '#f3f4f6',
        letterSpacing: 0,
        lineHeight: 1.5,
      },
      {
        id: 'footer-profile',
        type: 'text',
        text: 'Siga @sua.agencia para conteúdos diários de escala e tráfego',
        x: 80,
        y: 1250,
        width: 920,
        height: 30,
        rotation: 0,
        opacity: 0.6,
        locked: false,
        zIndex: 7,
        fontFamily: 'Inter, system-ui, sans-serif',
        fontSize: 16,
        fontWeight: '500',
        fontStyle: 'normal',
        textAlign: 'center',
        color: '#9ca3af',
        letterSpacing: 1,
        lineHeight: 1.2,
      },
    ],
  },
];
